version: '3.8'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 1
        MYSQL_DATABASE: blog
        MYSQL_USER: admin
        MYSQL_PASSWORD: p4sSw0rd
    volumes:
        - ./db_data:/var/lib/mysql

  cuteshopv2:
    build: 
        context: ./app
    depends_on:
        - db
    restart: always
    environment:
        APP_PORT: 8080        
        MYSQL_DATABASE: blog
        MYSQL_USER: admin
        MYSQL_PASSWORD: p4sSw0rd
    ports:
        - 8080:8080

